apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: 205930645143.dkr.ecr.eu-north-1.amazonaws.com/result:latest
        ports:
        - containerPort: 80
