apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: my-node-app:latest
        ports:
        - containerPort: 80
